config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  match '/404',                       to: 'errors#not_found',       as: :not_found,       via: :all
  match '/422',                       to: 'errors#unacceptable',    as: :unacceptable,    via: :all
  match '/500',                       to: 'errors#internal_error',  as: :internal_error,  via: :all

  get   '/contact',                   to: 'static_pages#contact',   as: :contact
  get   '/faq',                       to: 'static_pages#faq',       as: :faq

  get   'twitch/salty/sign_in',       to: 'twitch#to_twitch',       as: :to_twitch
  get   'twitch/salty/auth',          to: 'twitch#from_twitch',     as: :twitch_auth
  get   'twitch/salty/sign_out',      to: 'twitch#sign_out',        as: :sign_out

  get   'twitch/salty',               to: 'users#salty',            as: :salty
  patch 'twitch/salty',               to: 'users#update',           as: :update_salty
  get   'twitch/salty/quotes',        to: 'users#quotes',           as: :salty_quotes
  patch 'twitch/salty/quotes',        to: 'users#q_update',         as: :update_salty_quotes
  get   'twitch/salty/custom',        to: 'users#custom_commands',  as: :custom_commands
  patch 'twitch/salty/custom',        to: 'users#cc_update',        as: :update_custom_commands
  get   'twitch/salty/guide',         to: 'users#guide',            as: :salty_guide

  get   'twitch/pydash/out',          to: 'dashboard#to_twitch',    as: :dashboard_out
  get   'twitch/pydash/auth',         to: 'dashboard#from_twitch',  as: :dashboard_auth

  get   'twitch/pydash',              to: 'dashboard#dashboard',    as: :dashboard

  # API Stuff
  namespace :api do
    resources :users, only: [] do
      scope module: :users do
        resources :quotes, only: [:index, :create, :update, :destroy]
        resources :puns, only: [:index, :create, :update, :destroy]
        resources :custom_commands, only: [:create, :destroy]
        resources :songs, only: [:index, :create, :update]
      end
    end

    resources :songs, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one   :settings, dependent: :destroy
  has_one   :song, dependent: :destroy
  has_many  :commands, dependent: :destroy
  has_many  :custom_commands, dependent: :destroy
  has_many  :quotes, dependent: :destroy
  has_many  :puns, dependent: :destroy
  accepts_nested_attributes_for :settings
  accepts_nested_attributes_for :commands
  accepts_nested_attributes_for :custom_commands
  accepts_nested_attributes_for :quotes
  accepts_nested_attributes_for :puns

  validates_presence_of :twitch_name, :twitch_id

  validates_with OauthValidator

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def commands
    {
      "commands"    => Command.new(name: "commands",    on: false, admin: false, limit: 30),
      "quote"       => Command.new(name: "quote",       on: false, admin: false, limit: 30),
      "addquote"    => Command.new(name: "addquote",    on: false, admin: false, limit: 30),
      "pun"         => Command.new(name: "pun",         on: false, admin: false, limit: 30),
      "addpun"      => Command.new(name: "addpun",      on: false, admin: false, limit: 30),
      "8ball"       => Command.new(name: "8ball",       on: false, admin: false, limit: 30),
      "uptime"      => Command.new(name: "uptime",      on: false, admin: false, limit: 30),
      "highlight"   => Command.new(name: "highlight",   on: false, admin: false, limit: 30),

      "wr"          => Command.new(name: "wr",          on: false, admin: false, limit: 30),
      "leaderboard" => Command.new(name: "leaderboard", on: false, admin: false, limit: 30),
      "pb"          => Command.new(name: "pb",          on: false, admin: false, limit: 30),
      "splits"      => Command.new(name: "splits",      on: false, admin: false, limit: 30),
      "race"        => Command.new(name: "race",        on: false, admin: false, limit: 30),

      "song"        => Command.new(name: "song",        on: false, admin: false, limit: 30),
      "rank"        => Command.new(name: "rank",        on: false, admin: false, limit: 30)

      # "runes"       => Command.new(name: "runes",       on: false, admin: false, limit: 30),
      # "masteries"   => Command.new(name: "masteries",   on: false, admin: false, limit: 30)
    }.merge(super.map{ |command| {command.name => command} }.inject(:merge) || {}).values
  end
end

app/controllers/api/users/custom_command_controller.rb
class Api::Users::CustomCommandsController < Api::ApplicationController
  before_action :set_user, only: [:update, :destroy]
  before_action :authenticate, only: [:update, :destroy]
  before_action :set_custom_command, only: [:update, :destroy]

  def update
    if @c_command.save
      render status: 200, json: {status: 200, message: "Custom command '#{params[:id]}' updated successfully."}
    else
      render status: 400, json: {status: 400, message: "Custom command '#{params[:id]}' failed to update."}
    end
  end

  def destroy
    if @c_command.destroy
      render status: 200, json: {status: 200, message: "Custom command '#{params[:id]}' destroyed."}
    else
      render status: 400, json: {status: 200, message: "Custom command '#{params[:id]}' could not be destroyed."}
    end
  end

  private

    def set_custom_command
      @c_command = Customcommand.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render status: 404, json: {status: 404, message: "Custom command with '#{params[:id]}' not found."}
    end
end

app/controllers/api/users/custom_commands_controller.rb
class Api::Users::CustomCommandsController < Api::ApplicationController
  before_action :set_user, only: [:create, :destroy]
  before_action :authenticate, only: [:create, :destroy]
  before_action :set_custom_command, only: [:destroy]

  def create
    @c_com = CustomCommand.new(user_id: @user.id, on: params[:on], trigger: params[:trigger], admin: params[:admin], limit: params[:limit], output: params[:output], help_text: params[:help_text])
    if @c_com.save
      send_update
      render status: 200, json: {status: 200, custom_command: @c_com}
    else
      render status: 400, json: {status: 400, error: "Failed to create custom command."}
    end
  end

  def destroy
    if @c_command.destroy
      send_update
      render status: 200, json: {status: 200, message: "Custom command '#{params[:id]}' destroyed."}
    else
      render status: 400, json: {status: 200, error: "Custom command '#{params[:id]}' could not be destroyed."}
    end
  end

  private

    def set_custom_command
      @c_command = CustomCommand.find_by!(user_id: @user.id, trigger: params[:id])
    rescue ActiveRecord::RecordNotFound
      render status: 404, json: {status: 404, error: "Custom command with '#{params[:id]}' not found."}
    end
end

app/controllers/api/users/puns_controller.rb
class Api::Users::PunsController < Api::ApplicationController
  before_action :set_user
  before_action :check_for_puns, only: [:index]
  before_action :authenticate, only: [:create, :update, :destroy]
  before_action :set_util, only: [:update, :destroy]

  def index
    check_reviewed(@user.puns)
    render status: 200, json: {
      status: 200,
      puns: @r_text.sample(limit).map { |pun| {text: pun.text} }
    }
  end

  def create
    @pun = Pun.new(user_id: @user.id, reviewed: params[:reviewed], text: params[:text])
    if @pun.save
      render status: 200, json: {
        status: 200,
        pun: @pun
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Failed to save."
      }
    end
  end

  def update
    if @tutil.update(:reviewed, params[:reviewed])
      render status: 200, json: {
        status: 200,
        pun: @tutil
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Something went wrong"
      }
    end
  end

  def destroy
    if @tutil.destroy
      render status: 200, json: {
        status: 200,
        message: "Successfully destroyed"
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Something went wrong"
      }
    end
  end

  private

    def check_for_puns
      if @user.puns.empty?
        render status: 400, json: {status: 400, error: "No puns for this user."}
      end
    end
end

app/controllers/api/users/quotes_controller.rb
class Api::Users::QuotesController < Api::ApplicationController
  before_action :set_user
  before_action :check_for_quotes, only: [:index]
  before_action :authenticate, only: [:create, :update, :destroy]
  before_action :set_util, only: [:update, :destroy]

  def index
    check_reviewed(@user.quotes)
    render status: 200, json: {
      status: 200,
      quotes: @r_text.sample(limit).map { |quote| {text: quote.text} }
    }
  end

  def create
    @quote = Quote.new(user_id: @user.id, reviewed: params[:reviewed], text: params[:text])
    if @quote.save
      render status: 200, json: {
        status: 200,
        quote: @quote
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Failed to save."
      }
    end
  end

  def update
    if @tutil.update :reviewed, params[:reviewed]
      render status: 200, json: {
        status: 200,
        quote: @tutil
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Something went wrong"
      }
    end
  end

  def destroy
    if @tutil.destroy
      render status: 200, json: {
        status: 200,
        message: "Successfully destroyed"
      }
    else
      render status: 400, json: {
        status: 400,
        error: "Something went wrong"
      }
    end
  end

  private

    def check_for_quotes
      if @user.quotes.empty?
        render status: 400, json: {status: 400, message: "No quotes for this user."}
      end
    end
end

app/controllers/api/users/songs_controller.rb
class Api::Users::SongsController < Api::ApplicationController
  before_action :set_user
  before_action :set_song
  before_action :authenticate, only: [:update]

  def index
    render status: 200, json: {
      status: 200,
      mapName: @song.map_name,
      mapId: @song.map_id,
      setId: @song.set_id
    }
  end

  def update
    if @user.settings.update(osu_song_key: User.digest(SecureRandom.urlsafe_base64.to_s))
      render stauts: 200, json: { status: 200, new_key: @user.settings[:osu_song_key] }
    else
      render status: 400, json: { stauts: 400, error: 'Error updating key.' }
    end
  end

  private

  def set_song
    @song = @user.song
    head :no_content unless @song
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :q_update, :cc_update]
  before_action :authenticate, only: [:update, :q_update, :cc_update]

  def salty
  end

  def update
    if @user.update(user_params.reject{|k, v| k.to_s == "bot_oauth" && v.blank?})
      if send_update
        flash[:success] = "Settings Saved"
      else
        flash[:warning] = "Settings could not be updated in the bot."
      end
    else
      flash[:danger] = "There was an error saving your settings.\n" + @user.errors.full_messages.join('\n')
    end

    redirect_to salty_path
  end

  def quotes
  end

  def q_update
    if @user.update(user_params)
      flash[:success] = "Quotes/Puns Updated"
    else
      flash[:danger] = "There was a problem updating the quotes and puns."
    end
    redirect_to salty_quotes_path
  end

  def custom_commands
  end

  def cc_update
    if @user.update(user_params)
      if send_update
        flash[:success] = "Custom Commands Updated"
      else
        flash[:warning] = "Custom commands could not be updated in the bot."
      end
    else
      flash[:danger] = "There was a problem updating your custom commands."
    end
    redirect_to custom_commands_path
  end

  def guide
  end

  private

  def user_params
    params.require(:user).permit({:settings_attributes => [:id, :active, :youtube_link, :osu_link,
                                  :social_active, :social_output, :social_time, :social_messages,
                                  :toobou_active, :toobou_limit, :toobou_trigger, :toobou_output,
                                  :voting_active, :voting_mods, :sub_message_active, :sub_message_text, :sub_message_resub]},
                                  :twitch_name, :bot_nick, :bot_oauth, :srl_nick, :osu_nick, :summoner_name, :speedruncom_nick,
                                  :commands_attributes => [:id, :name, :on, :admin, :limit],
                                  :custom_commands_attributes => [:id, :trigger, :on, :admin, :limit, :output],
                                  :quotes_attributes => [:id, :text, :reviewed],
                                  :puns_attributes => [:id, :text, :reviewed])
  end

  def set_user
    unless (@user = User.find_by(twitch_name: params[:user][:twitch_name]))
      raise ActiveRecord::RecordNotFound.new('Not Found')
    end
  end

  def authenticate
    render status: 403, text: '403 Unauthorized' unless current_user == @user
  end
end

app/views/users/custom_commands.haml
= provide(:title, "Custom Commands")
- if signed_in?
  #sub-header.row
    .col-sm-4
      = "You are signed in as #{@current_user.twitch_name}."
    .col-sm-8.text-end
      = render partial: "shared/buttons", locals: {path: :custom_commands}

  = form_for @current_user, url: update_custom_commands_path do |f|
    = f.hidden_field :twitch_name
    %h1 Custom Commands
    %h2 Please do not add prefixes for commands, they will be added automatically (ex: !)
    #custom-commands-form
      .row
        = f.fields_for :custom_commands do |cc|
          .col-xs-12.col-md-6{id: "ccustom-#{cc.object.id}"}
            .custom-command.border
              = cc.check_box :on, class: "form-check-input"
              = cc.label :on, "Enabled", class: "form-check-label"

              .form-check
                = cc.check_box :admin, class: "form-check-input"
                = cc.label :admin, "Mod Only Command", class: "form-check-label"

              = cc.label :trigger, "Command Trigger:", class: "form-label"
              = cc.text_field :trigger, class: "form-control"

              = cc.label :limit, "Limit:", class: "form-label"
              = cc.number_field :limit, class: "form-control"

              = cc.label :output, "Output:", class: "form-label"
              = cc.text_field :output, class: "form-control"

              = cc.label :help_text, "Help Text:", class: "form-label"
              = cc.text_field :help_text, class: "form-control"

              %button.btn.btn-danger{type: "button", id: "delete-#{cc.object.id}", onclick: "window.delete_custom_command({user: '#{@current_user.twitch_name}', id: '#{cc.object.id}', trigger: '#{cc.object.trigger}'});"}
                Delete

    = f.submit "Save", class: "btn btn-primary w-auto"

  %h2 Add New Commands
  #new-custom.row
    .col-xs-12.col-md-6
      %label.form-label{for: "new-trigger"} Trigger:
      %input#new-trigger.form-control{type: "text", name:"new-trigger"}

      .form-check
        %input#new-admin.form-check-input{type: "checkbox", name: "new-admin"}
        %label.form-check-label{for: "new-admin"} Mod Command?

      %label.form-label{for: "new-limit"} Limit:
      %input#new-limit.form-control{type: "number", name: "new-limit"}

      %label.form-label{for: "new-output"} Output:
      %input#new-output.form-control{type: "text", name: "new-output"}

      %label.form-label{for: "new-help-text"} Help Text:
      %input#new-help-text.form-control{type: "text", name: "new-help-text"}

      %button.btn.btn-primary{type: "button", onclick: "window.create_custom_command({user: '#{@current_user.twitch_name}', on: true, trigger: $('#new-trigger').val(), admin: $('#new-admin').is(':checked'), limit: $('#new-limit').val(), output: $('#new-output').val(), help_text: $('#new-help-text').val()})"}
        Create New Command

- else
  Please sign in on the main salty page located
  = link_to "here.", salty_path

app/views/users/guide.html.haml
= provide(:title, "Guide Thingy")
There will be a guide here for everything salty related when I have more time.

app/views/users/quotes.haml
= provide(:title, "Quotes")
- if signed_in?
  #sub-header.row
    .col-sm-4
      = "You are signed in as #{@current_user.twitch_name}."
    .col-sm-8.text-end
      = render partial: "shared/buttons", locals: {path: :quotes}

  = form_for @current_user, url: update_salty_quotes_path do |f|
    = f.hidden_field :twitch_name
    %h1 Quotes
    .row.mb-3
      = f.fields_for :quotes do |d|
        .col-xs-12.col-md-6{id: "quotes-#{d.object.id}"}
          .textutil
            = d.text_field :text, class: "form-control"
            - unless d.object.reviewed
              %button.btn.btn-success.text-approve-button{type: "button", id: "approve-#{d.object.id}", data: {user: @current_user.twitch_name, type: "quotes", id: d.object.id}}
                Approve

            %button.btn.btn-danger.text-delete-button{type: "button", data: {id: d.object.id, type: "quotes", user: @current_user.twitch_name}}
              Delete

    #new-qoute
      %input#new_quotes_input.form-control{type: "text", name: "new_quote_input"}
      %button.btn.btn-primary{type: "button", onclick: "window.create_textutil({user: '#{@current_user.twitch_name}', type: 'quotes', text: $('#new_quotes_input').val()});"}
        Create New Quote

    %h1 Puns
    .row.mb-3
      = f.fields_for :puns do |d|
        .col-xs-12.col-md-6{id: "puns-#{d.object.id}"}
          .textutil
            = d.text_field :text, class: "form-control"
            - unless d.object.reviewed
              %button.btn.btn-success.text-approve-button{type: "button", id: "approve-#{d.object.id}", data: {user: @current_user.twitch_name, id: d.object.id, type: "puns"}}
                Approve

            %button.btn.btn-danger.text-delete-button{type: "button", id: "delete-#{d.object.id}", data: {user: @current_user.twitch_name, id: d.object.id, type: "puns"}}
              Delete

      #new-pun
        %input#new_puns_input.form-control{type: "text", name:"new_pun_input"}
        %button.btn.btn-primary{type: "button", onclick: "window.create_textutil({user: '#{@current_user.twitch_name}', type: 'puns', text: $('#new_puns_input').val()});"}
          Create New Pun

    = f.submit "Save", class: "btn btn-primary w-auto"

- else
  %div Please sign in on the main salty page located
  = link_to "here.", salty_path

app/views/users/salty.haml
= provide(:title, "SaltyBot")
- if signed_in?
  #sub-header.row
    .col-sm-4
      = "You are signed in as #{@current_user.twitch_name}."
    .col-sm-8.text-end
      = render partial: "shared/buttons", locals: {path: :salty}

  = form_for @current_user, url: update_salty_path do |f|
    %h1 General Info
    .form-check.mb-3
      = f.fields_for :settings do |d|
        = d.check_box :active, class: "form-check-input"
        = d.label :active, class: "form-check-label" do
          Enable Bot In Your Channel

    .row
      .col-xs-12.col-md-6
        = f.label :twitch_name, "Channel to Join:", class: "form-label"
        = f.text_field :twitch_name, readonly: true, class: "form-control"

        = f.label :bot_nick, class: "form-label" do
          Bot Nick to Use:
          .mini-text *Leave blank if using default name of TheSaltyBot
        = f.text_field :bot_nick, placeholder: "TheSaltyBot", class: "form-control"

        = f.label :bot_oauth, class: "form-label" do
          Oauth for Bot Nick:
          .mini-text *Leave blank if using default name
        = f.password_field :bot_oauth, class: "form-control"

      .col-xs-12.col-md-6
        = f.label :srl_nick, "SpeedRunsLive Nick:", class: "form-label"
        = f.text_field :srl_nick, class: "form-control"

        = f.label :speedruncom_nick, class: "form-label" do
          Speedrun.com Username:
          .mini-text *Optional if twitch name is exactly the same
        = f.text_field :speedruncom_nick, class: "form-control"

        = f.label :osu_nick, "Osu Nick:", class: "form-label"
        = f.text_field :osu_nick, class: "form-control"

    - counter = 0
    = f.fields_for :commands do |d|
      - counter = counter + 1
      - if counter == 1
        %h1 General Commands
        <div class="row g-0 mb-3">
      - elsif counter == 9
        </div>
        %h1 Speedrunning Commands
        <div class="row g-0 mb-3">
      - elsif counter == 14
        </div>
        %h1 Osu Commands
        <div class="row g-0 mb-3">


      .col-xs-12.col-md-4
        .card
          .card-header.bg-dark.text-light
            %h2.command-heading= "!#{d.object.name}"
          .card-body
            = d.hidden_field :name
            .form-check
              = d.check_box :on, class: "form-check-input"
              = d.label :on, class: "form-check-label" do
                Enabled
            .form-check
              = d.check_box :admin, class: "form-check-input"
              = d.label :admin, class: "form-check-label" do
                Mod Only Command?

            = d.label :limit, "Cooldown:", class: "form-check-label"
            = d.number_field :limit, min: 0, class: "form-control"

    </div>
    .h1 Random Options
    = f.fields_for :settings do |d|
      .form-check
        = d.check_box :youtube_link, class: "form-check-input"
        = d.label :youtube_link, class: "form-check-label" do
          Link YouTube Videos In Chat?
      .form-check
        = d.check_box :osu_link, class: "form-check-input"
        = d.label :osu_link, class: "form-check-label" do
          Send Osu Songs In Chat To Game Chat?

      .row.mb-3
        .col-xs-12.col-md-4
          .card
            .card-header.bg-dark.text-light
              %h2.command-heading Sub Messages
            .card-body
              .form-check
                = d.check_box :sub_message_active, class: "form-check-input"
                = d.label :sub_message_active, class: "form-check-label" do
                  Have Bot Say a Message When User Subs

              = d.label :sub_message_text, "Regular Sub:", class: "form-check-label"
              = d.text_field :sub_message_text, class: "form-control"

              = d.label :sub_message_resub, "Resubscription:", class: "form-check-label"
              = d.text_field :sub_message_resub, class: "form-control"

        .col-xs-12.col-md-4
          .card
            .card-header.bg-dark.text-light
              %h2.command-heading Social
            .card-body
              .form-check
                = d.check_box :social_active, class: "form-check-input"
                = d.label :social_active, class: "form-check-label" do
                  Have bot say messages at regular intervals (minutes)

              = d.label :social_output, "Output:", class: "form-check-label"
              = d.text_field :social_output, class: "form-control"

              = d.label :social_time, "Time Between Messgaes:", class: "form-check-label"
              = d.number_field :social_time, min: 0, class: "form-control"

              = d.label :social_messages, "Number of Messages Inbetween Outputs:", class: "form-check-label"
              = d.number_field :social_messages, min: 0, class: "form-control"

        .col-xs-12.col-md-4
          .card
            .card-header.bg-dark.text-light
              %h2.command-heading Toobou
            .card-body
              .form-check
                = d.check_box :toobou_active, class: "form-check-input"
                = d.label :toobou_active, class: "form-check-label" do
                  Say something based on words in chat

              = d.label :toobou_limit, "Cooldown:", class: "form-check-label"
              = d.number_field :toobou_limit, min: 0, class: "form-control"

              = d.label :toobou_trigger, "Tigger:", class: "form-check-label"
              = d.text_field :toobou_trigger, class: "form-control"

              = d.label :toobou_output, "Output:", class: "form-check-label"
              = d.text_field :toobou_output, class: "form-control"

    = f.submit "Save", class: "btn btn-primary w-auto"
- else
  = link_to "Login with Twitch", to_twitch_path, class: "btn btn-primary"
  This page is the web interface for SaltyBot.  If you would like to use it just log in to this page using Twitch and select the options that you would like.