config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'

  match '/404',                       to: 'errors#not_found',       as: :not_found,       via: :all
  match '/422',                       to: 'errors#unacceptable',    as: :unacceptable,    via: :all
  match '/500',                       to: 'errors#internal_error',  as: :internal_error,  via: :all

  get   '/contact',                   to: 'static_pages#contact',   as: :contact
  get   '/faq',                       to: 'static_pages#faq',       as: :faq

  get   'twitch/salty/sign_in',       to: 'twitch#to_twitch',       as: :to_twitch
  get   'twitch/salty/auth',          to: 'twitch#from_twitch',     as: :twitch_auth
  get   'twitch/salty/sign_out',      to: 'twitch#sign_out',        as: :sign_out

  get   'twitch/salty',               to: 'users#salty',            as: :salty
  patch 'twitch/salty',               to: 'users#update',           as: :update_salty
  get   'twitch/salty/quotes',        to: 'users#quotes',           as: :salty_quotes
  patch 'twitch/salty/quotes',        to: 'users#q_update',         as: :update_salty_quotes
  get   'twitch/salty/custom',        to: 'users#custom_commands',  as: :custom_commands
  patch 'twitch/salty/custom',        to: 'users#cc_update',        as: :update_custom_commands
  get   'twitch/salty/guide',         to: 'users#guide',            as: :salty_guide

  get   'twitch/pydash/out',          to: 'dashboard#to_twitch',    as: :dashboard_out
  get   'twitch/pydash/auth',         to: 'dashboard#from_twitch',  as: :dashboard_auth

  get   'twitch/pydash',              to: 'dashboard#dashboard',    as: :dashboard

  # API Stuff
  namespace :api do
    resources :users, only: [] do
      scope module: :users do
        resources :quotes, only: [:index, :create, :update, :destroy]
        resources :puns, only: [:index, :create, :update, :destroy]
        resources :custom_commands, only: [:create, :destroy]
        resources :songs, only: [:index, :create, :update]
      end
    end

    resources :songs, only: [:create]
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %div{style: "text-align: center;"}
    %a{href: contact_path} Contact Us
    |
    %a{href: "https://www.github.com/batedurgonnadie/salty_bot", target: "_blank"} Bot Repo
    |
    %a{href: "https://www.github.com/batedurgonnadie/salty_web", target: "_blank"} Web Repo
    |
    %a{href: "https://discord.gg/uHGUA4a", target: :_blank} Discord

app/views/layouts/_header.html.haml
%header.navbar.navbar-expand.navbar-dark.bg-dark
  .container
    = link_to "League of Newbs", root_path, id: "logo", class: "navbar-brand"
    %nav
      %ul.navbar-nav.navbar-right
        %li.navbar-item= link_to "Home", root_path, class: "nav-link #{request.path == root_path ? " active" : ""}"
        %li.navbar-item= link_to "FAQ", faq_path, class: "nav-link #{request.path == faq_path ? " active" : ""}"
        %li.navbar-item= link_to "PyDash", dashboard_path, class: "nav-link #{request.path == dashboard_path ? " active" : ""}"
        %li.navbar-item= link_to "SaltyBot", salty_path, class: "nav-link #{request.path == salty_path ? " active" : ""}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title= yield :title
    = stylesheet_link_tag "application.css"
    = javascript_include_tag "application.js", async: Rails.env.production?, defer: Rails.env.production?
    = csrf_meta_tags
    = favicon_link_tag
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{class: "alert alert-#{key} alert-dismissible fade show", role: "alert"}
          = value
          %button.btn-close{type: "button", "data-bs-dismiss" => "alert", "aria-label" => "Close"}
      = yield
      = render 'layouts/footer'

    - if signed_in?
      = render 'modals/song_command'